version: "3.8"

services:
  php:
    build: .
    container_name: meu-php
    restart: unless-stopped
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: meu-nginx
    restart: unless-stopped
    ports:
      - "4000:80"  # Nginx estará acessível na porta 4000
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php